# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  custom: # Pipelines that are triggered manually
    version-bump:
      - step:
          image: python:latest
          script: # Modify the commands below to build your repository.
            - cd tools
            - sh versionBump.sh
            - cd ..
  default:  # Pipelines that run automatically on any commit
    - step:
        image: node:latest
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y zip
          - sh tools/build.sh
